p8105_hw2_sm4956
================
Shivangi Deepak Mewada

## Problem 0

-   created repository and R project for HW2, created rmd file and
    rending to GitHub.
-   created a sub-directory/ data folder that has all the data set files
    to be used for this HW

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
options(tibble.print_min = 5)
```

## Problem 1

reading and cleaning data, retaining important variables

``` r
trans_ent = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

To check the number of distinct stations:

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##   station_name line    
    ##   <chr>        <chr>   
    ## 1 25th St      4 Avenue
    ## 2 36th St      4 Avenue
    ## 3 45th St      4 Avenue
    ## 4 53rd St      4 Avenue
    ## 5 59th St      4 Avenue
    ## # … with 460 more rows

To check the number of distinct stations that are ADA Compliant:

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##   station_name             line           
    ##   <chr>                    <chr>          
    ## 1 Atlantic Av-Barclays Ctr 4 Avenue       
    ## 2 DeKalb Av                4 Avenue       
    ## 3 Pacific St               4 Avenue       
    ## 4 Grand Central            42nd St Shuttle
    ## 5 34th St                  6 Avenue       
    ## # … with 79 more rows

To see the proportion of station entrances/exits without vending allow
entrance:

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

To check the distinct stations serving A trains (and the ones that are
ADA Compliant):

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##   station_name                  line           
    ##   <chr>                         <chr>          
    ## 1 Times Square                  42nd St Shuttle
    ## 2 125th St                      8 Avenue       
    ## 3 145th St                      8 Avenue       
    ## 4 14th St                       8 Avenue       
    ## 5 168th St - Washington Heights 8 Avenue       
    ## # … with 55 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

### Answers

-   There are 465 distinct stations.
-   There are 84 distinct stations, that are ADA compliant.
-   the proportion of station entrances / exits without vending allow
    entrance is 0.38.
-   There are 60 distinct stations, that serve the A train.
-   There are 17 distinct stations, that serve the A train and are ADA
    compliant.

## Problem 2

Reading and cleaning the data set for Mr Trash Wheel

``` r
trash_W1 = 
  readxl::read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N549") %>%
  janitor::clean_names() %>%
  drop_na (dumpster) %>%
mutate (
        sports_balls = as.integer(sports_balls),
        wheel = "mrtrash")
```

Now, I will repeat the same for Professor Trash Wheel

``` r
prof_W2 = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M96") %>%
  janitor::clean_names() %>%
  drop_na (dumpster) %>%
mutate (year = as.character(year),
       wheel = "proftrash" )
```

Combining both the data sets:

``` r
merged_trash = bind_rows (trash_W1, prof_W2) %>%
  janitor::clean_names()
```

### Description of the data set post merging:

|                                                  |              |
|:-------------------------------------------------|:-------------|
| Name                                             | merged_trash |
| Number of rows                                   | 641          |
| Number of columns                                | 15           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |              |
| Column type frequency:                           |              |
| character                                        | 3            |
| numeric                                          | 11           |
| POSIXct                                          | 1            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |              |
| Group variables                                  | None         |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| month         |         0 |             1 |   3 |   9 |     0 |       13 |          0 |
| year          |         0 |             1 |   4 |   4 |     0 |        9 |          0 |
| wheel         |         0 |             1 |   7 |   9 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |     mean |       sd |     p0 |     p25 |     p50 |      p75 |      p100 | hist  |
|:-------------------|----------:|--------------:|---------:|---------:|-------:|--------:|--------:|---------:|----------:|:------|
| dumpster           |         0 |          1.00 |   240.78 |   166.88 |   1.00 |   81.00 |  227.00 |   387.00 |    547.00 | ▇▅▅▅▅ |
| weight_tons        |         0 |          1.00 |     3.02 |     0.84 |   0.61 |    2.48 |    3.08 |     3.62 |      5.62 | ▁▅▇▅▁ |
| volume_cubic_yards |         0 |          1.00 |    15.22 |     1.44 |   6.00 |   15.00 |   15.00 |    15.00 |     20.00 | ▁▁▁▇▁ |
| plastic_bottles    |         0 |          1.00 |  2464.81 |  1817.94 | 210.00 | 1110.00 | 2110.00 |  3100.00 |   9830.00 | ▇▆▁▁▁ |
| polystyrene        |         0 |          1.00 |  2088.81 |  1990.25 |  48.00 |  780.00 | 1460.00 |  2870.00 |  11528.00 | ▇▃▁▁▁ |
| cigarette_butts    |         0 |          1.00 | 19663.80 | 28187.00 | 900.00 | 4400.00 | 8000.00 | 23000.00 | 310000.00 | ▇▁▁▁▁ |
| glass_bottles      |         0 |          1.00 |    20.71 |    15.82 |   0.00 |    9.00 |   18.00 |    28.00 |    110.00 | ▇▃▁▁▁ |
| grocery_bags       |         0 |          1.00 |  1217.66 |  1634.36 |  24.00 |  360.00 |  780.00 |  1480.00 |  13450.00 | ▇▁▁▁▁ |
| chip_bags          |         0 |          1.00 |  2405.54 |  3050.01 | 180.00 |  800.00 | 1340.00 |  2684.00 |  20100.00 | ▇▁▁▁▁ |
| sports_balls       |        94 |          0.85 |    12.56 |     9.28 |   0.00 |    6.00 |   11.00 |    18.00 |     56.00 | ▇▅▂▁▁ |
| homes_powered      |        73 |          0.89 |    44.11 |    20.73 |   0.00 |   34.67 |   49.00 |    57.50 |     93.67 | ▂▃▇▅▁ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min        | max        | median     | n_unique |
|:--------------|----------:|--------------:|:-----------|:-----------|:-----------|---------:|
| date          |         0 |             1 | 1900-01-20 | 2022-07-29 | 2018-08-09 |      359 |

-   The total number of observations/rows are **641** and the total
    number of variables/columns are **15**
-   There are 3 character variables, 11 numeric variables and 1 date
    variable
-   The main variables in the data set are weight of the trash (in
    tons), volume of the trash (in cubic yards) and the amount of
    various types of trash collected like plastic bottles, chips bags,
    cigarette butts, glass bottles, sports balls, polystyrene), the
    homes powered, and the distribution by names (Mr and Prof Trash).
-   The total weight of trash collected combined is **1938.48** tons
-   The total weight of trash collected by Professor Trash is **190.12**
    tons
-   The total number of sports balls collected by Mr Trash is **856**
